Add Ampere87 (orin nano) as a valid target architecture) (#8092)
* SYCL: Workaround issues with sycl::select_from_group for pointers in oneAPI 2025.0.4 (#8051)

* SYCL: Workaround issues with sycl::select_from_group for pointers in oneAPI 2025.0.4

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* fix gfx90a in makefiles (#8067)

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Add Ampere87 (orin nano) as a valid target architecture)

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* resolve merge conflict

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Improve clarity on max_threads

Co-authored-by: JBludau <104908666+JBludau@users.noreply.github.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* fix formatting

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* kokkos(profiling): pass by reference

Signed-off-by: romintomasetti <romin.tomasetti@gmail.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* fix accidental c-style-cast in create_data_handle

Signed-off-by: Nicolas Morales <nmmoral@sandia.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* fix other accidental c-style-casts of data_handle_type

Signed-off-by: Nicolas Morales <nmmoral@sandia.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Merge pull request #8073 from masterleinad/update_mdspan

Update bundled mdspan

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* New View implementation: Disallow constructing managed View with Kokkos::MemoryUnmanaged trait

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* OpenMPTarget / OpenACC: Keep locks array access in-bounds (#8077)

* OpenMPTarget: Keep locks array access in-bounds

Signed-off-by: Carl Pearson <cwpears@sandia.gov>

* OpenACC: Keep locks array access in-bounds

Signed-off-by: Carl Pearson <cwpears@sandia.gov>

---------

Signed-off-by: Carl Pearson <cwpears@sandia.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix a memory leak in the initialization
- Make some variables static to avoid memory leaks if `std::exit` is
  called during initialization

Signed-off-by: Trévis Morvany <trevis.morvany@cea.fr>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* fix a broken link in README.md

Signed-off-by: Miroslav Stoyanov <stoyanovmk@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* An easier to maintain parallel_reduce implementation (#8060)

* A simpler parallel_reduce implementation: first draft

* Retain only the necessary static_asserts

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Avoid static variables and functions in header files. (#8071)

* Avoid static variables and functions in header files.

* Revert changes to static member function

---------

Co-authored-by: Damien L-G <dalg24@gmail.com>
Co-authored-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Rework note at the end of the help message and ask users to cite Kokkos (#8057)

* Improve help message: add a reference to our website

and ask users to cite Kokkos in their work

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Point to kokkos.org for citiations.

Signed-off-by: Christian Trott <crtrott@sandia.gov>

* Apply suggestions from code review

Co-authored-by: Damien L-G <dalg24+github@gmail.com>

---------

Signed-off-by: Damien L-G <dalg24@gmail.com>
Signed-off-by: Christian Trott <crtrott@sandia.gov>
Co-authored-by: Christian Trott <crtrott@sandia.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Exit early at initialize when the user queries the kokkos help (#8079)

* Exit early at initialize when the user queries kokkos-help

Causes normal program termination when the `--kokkos-help` flag is found.
I can't think of examples where one would explicitly pass it as command
line argument and still want the program to continue.
This does not change the behavior with `--help` (unprefixed).

* Add test for exit early on kokkos help
* Fix Stack buffer overflow reported by AddressSanitizer

---------

Signed-off-by: Damien L-G <dalg24@gmail.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Enable bugprone-signed-char-misuse check (#8086)

* Suppress false positive (bugprone-signed-char-misuse)

Not applicable here as we are not working with non-ASCII characters,
just small integers

* Enable bugprone-signed-char-misuse check

---------

Signed-off-by: Damien L-G <dalg24@gmail.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Remove [[nodiscard]] from kokkos simd

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Bump github/codeql-action from 3.28.17 to 3.28.18

Bumps [github/codeql-action](https://github.com/github/codeql-action) from 3.28.17 to 3.28.18.
- [Release notes](https://github.com/github/codeql-action/releases)
- [Changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
- [Commits](https://github.com/github/codeql-action/compare/60168efe1c415ce0f5521ea06d5c2062adbeed1b...ff0a06e83cb2de871e5a09832bc6a81e7276941f)

---
updated-dependencies:
- dependency-name: github/codeql-action
  dependency-version: 3.28.18
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Add constructors for Random_XorShift*_Pool with execution space argument

Allows construction of instances with non-blocking initialization
occurring on a given execution space instance. Also useful when
multiple instances of a device are available, in which case the
execution space argument is used to select a device.

Signed-off-by: Martin Pokorny <mpokorny@caltech.edu>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Rework Random Generators according to my suggestion.

Signed-off-by: Christian Trott <crtrott@sandia.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* CMake: Remove unused export set

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Initial support for SVE

Signed-off-by: Minh Quan Ho <minh-quan.ho@sipearl.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* simd: Add generic ARM-SVE simd<T> backend for 128-bit and 256-bit SVE

- Support any ARMv8.4-a(+sve) processors, with 128-bit and 256-bit SVE
  (except 512-bit due to implementation limitation)
- Auto-detect SVE VL size at configure (CMake try_run()) on the
  running CPU and insert -msve-vector-bits=<VL> to compile flag.
- Enabled with KOKKOS_ARCH_NATIVE, KOKKOS_ARCH_ARMV84_SVE and
  KOKKOS_ARCH_ARMV9_GRACE

* Makefile.kokkos : add new arch ARMV84 and ARMV84_SVE
* cmake/KokkosCore_config.h.in : same
* cmake/kokkos_arch.cmake : same
                            ARMV9_GRACE compiled with -mcpu=neoverse-v2
* core/src/impl/Kokkos_Core.cpp : same
* cmake/compile_tests/get_sve_hw_vl.cpp : new helper C file to query HW SVE
                                          vector length
* simd/src/Kokkos_SIMD.hpp : declare new simd_abi for SVE and add
                             template <class T> to host_fixed_abi.
* simd/unit_tests/include/TestSIMD_Construction.hpp : same
* simd/src/Kokkos_SIMD_SVE.hpp : fix existing PR #7109 and finalize
                                     SVE implementation

Signed-off-by: Minh Quan Ho <minh-quan.ho@sipearl.com>

* Tests: robustify SIMD tests to handle unimplemented simd and simd_mask types

- simd: implementation of a simd<T, Abi> requires implicitly the
  availability of simd_mask<T, Abi> for comparison operators (<,>,=).
  The boolean tester 'is_type_v<>' is now extended to 'is_simd_avail_v<T, Abi>'
  to check for both simd<T, Abi> and simd_mask<T, Abi>.
- benchmarks: minor fixes to work with large data count
- cmake: check for presence of local googlebenchmark package instead of
  always downloading from internet.

* benchmarks/gups/gups.cpp: fix index type on large dataset
* simd/unit_tests/include/*.hpp: 'is_type_v<>' is now extended to
                                 'is_simd_avail_v<T, Abi>' to check for both
                                 simd<T, Abi> and simd_mask<T, Abi>
* simd/unit_tests/include/TestSIMD_Conversions.hpp: add test conversion
     with incremental integer vector and true-false alternated booleans,
     additional to current unique values.

Signed-off-by: Minh Quan Ho <minh-quan.ho@sipearl.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* simd-neon: instantiate explicitly basic_simd_mask<> on supported <T, abi>

- Should instantiate them so that the checker is_type_v<T, abi> can catch them

* simd/src/Kokkos_SIMD_NEON.hpp: add explicit basic_simd_mask<> instantiations

Signed-off-by: Minh Quan Ho <minh-quan.ho@sipearl.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* simd-sve: some minor reviews

- Edit basic_simd arithmetic operations to use _m suffix (except sve_mask)
- Add check warning in CMake configure time for arm_neon_sve_bridge.h

Signed-off-by: Minh Quan Ho <minh-quan.ho@sipearl.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Add initial View customization point (#8098)

* Add initial View customization point

This uses ADL based function lookup using functions that take
a Kokkos::Impl::ViewArguments (effectively typelist) arg.

Thus its not yet fully public, but can easily be made public.
It returns another special argument that speifies index_type
and accessor_type.

---------

Signed-off-by: Christian Trott <crtrott@sandia.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Deprecate Kokkos::MemoryManaged

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Introduce default template argument for MemoryTraits

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* SYCL: Allow requesting out-of-order queues (#8091)

* SYCL: Allow requesting out-of-order queues

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

* Add a CI build

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

* Disable SYCL graph support with out-of-order queues

* Disable thread-safety tests for out-of-order queues

* Don't run calng-tidy

* Fix formatting in core/unit_test/CMakeLists.txt

* CMake: Remove unused export set

* KOKKOS_IMPL_GRAPH_SUPPORT->KOKKOS_IMPL_SYCL_GRAPH_SUPPORT

* Change FIXME style

* KOKKOS_ENABLE_SYCL_OUT_OF_ORDER_QUEUES->KOKKOS_ENABLE_IMPL_SYCL_OUT_OF_ORDER_QUEUES

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

* Restore kokkos_tribits.cmake

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

* Fix KOKKOS_IMPL_SYCL_GRAPH_SUPPORT

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

* Change test inclusion style

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

---------

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Enable bugprone-exception-escape check (#8089)

* Drop noexcept specifier on tuners internals

Drop noexcept on Impl::ValueHierarchyNode::add_root_value() because the
specifiers make little sense there and they upset clang-tidy.

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppress clang-tidy warning on InitializationSettings getters

Signed-off-by: Damien L-G <dalg24@gmail.com>

* More bugprone-exception-escape suppressions

Signed-off-by: Damien L-G <dalg24@gmail.com>

* ViewCtorProp cleanup to resolve clang-tidy warning

Drop explicit defaulting of copy constructor and copy assignment
operator in ViewCtorProp which appear to resolve the following
clang-tidy warning:
```
<kokkos>/core/src/View/Kokkos_ViewCtor.hpp:183:8: warning: an exception may be thrown in function 'ViewCtorProp' which should not throw exceptions [bugprone-exception-escape]
  183 | struct ViewCtorProp : public ViewCtorProp<void, P>... {
      |        ^

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppressions for main

I opted for wholesale disabling in examples/tutorials to avoid poluting
our material with clang-tidy directives.
I think it is acceptable to annotate our tests and benchmarks.

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Enable bugprone-exception-escape check

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Strip noexcept specifier on all non-nested parallel_reduce

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Drop another couple bad noexcept specifier in "combined" reducers

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppress nonsensical bugprone-exception-escape warning

Could not figure out where it is coming from and how to properly
resolve it but the suppression works.
```
/tmp/kokkos/algorithms/unit_tests/../src/std_algorithms/Kokkos_IterSwap.hpp:56:6: error: an exception may be thrown in function 'iter_swap<Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::LayoutStride, Kokkos::SYCLDeviceUSMSpace>>, Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::LayoutStride, Kokkos::SYCLDeviceUSMSpace>>>' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
   56 | void iter_swap(IteratorType1 a, IteratorType2 b) {
      |      ^
/tmp/kokkos/algorithms/unit_tests/../src/std_algorithms/Kokkos_IterSwap.hpp:56:6: error: an exception may be thrown in function 'iter_swap<Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::SYCLDeviceUSMSpace>>, Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::SYCLDeviceUSMSpace>>>' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
```

Signed-off-by: Damien L-G <dalg24@gmail.com>

---------

Signed-off-by: Damien L-G <dalg24@gmail.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Add missing fence for async Random init with unified memory

Signed-off-by: Christian Trott <crtrott@sandia.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix warning in test

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Enable bugprone-branch-clone check (#8106)

* Suppress bugprone-branch-clone warnings in algorithms unit tests

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppress bugprone-branch-clone warnings in is_partitioned algo

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppress bugprone-branch-clone warnings in SIMD identity

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Enable bugprone-branch-clone check

Signed-off-by: Damien L-G <dalg24@gmail.com>

---------

Signed-off-by: Damien L-G <dalg24@gmail.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix stray bugprone-branch-clone warnings

Signed-off-by: Damien L-G <dalg24@gmail.com>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix copyright in cmake/compile_tests/get_sve_hw_vl.cpp

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix more formatting

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix unit tests, fix typo

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix unit test typo

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix unit test failures

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Fix unit test skipping mechanism

Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>

* Apply suggestions from code review

Fix format

---------

Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
Signed-off-by: Ovidiu Cristea <ocristea@gmail.com>
Signed-off-by: romintomasetti <romin.tomasetti@gmail.com>
Signed-off-by: Nicolas Morales <nmmoral@sandia.gov>
Signed-off-by: Carl Pearson <cwpears@sandia.gov>
Signed-off-by: Trévis Morvany <trevis.morvany@cea.fr>
Signed-off-by: Miroslav Stoyanov <stoyanovmk@ornl.gov>
Signed-off-by: Damien L-G <dalg24@gmail.com>
Signed-off-by: Christian Trott <crtrott@sandia.gov>
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Martin Pokorny <mpokorny@caltech.edu>
Signed-off-by: Minh Quan Ho <minh-quan.ho@sipearl.com>
Co-authored-by: Daniel Arndt <arndtd@ornl.gov>
Co-authored-by: JBludau <104908666+JBludau@users.noreply.github.com>
Co-authored-by: romintomasetti <romin.tomasetti@gmail.com>
Co-authored-by: Nicolas Morales <nmmoral@sandia.gov>
Co-authored-by: Carl Pearson <cwpearson@users.noreply.github.com>
Co-authored-by: Trévis Morvany <trevis.morvany@cea.fr>
Co-authored-by: Miroslav Stoyanov <stoyanovmk@ornl.gov>
Co-authored-by: Hariprasad Kannan <3788945+science-enthusiast@users.noreply.github.com>
Co-authored-by: Wolfgang Bangerth <bangerth@colostate.edu>
Co-authored-by: Damien L-G <dalg24@gmail.com>
Co-authored-by: Christian Trott <crtrott@sandia.gov>
Co-authored-by: Dong Hun Lee <donlee@sandia.gov>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Martin Pokorny <mpokorny@caltech.edu>
Co-authored-by: Minh Quan Ho <minh-quan.ho@sipearl.com>
Co-authored-by: Damien L-G <dalg24+github@gmail.com>