Enable bugprone-exception-escape check (#8089)
* Drop noexcept specifier on tuners internals

Drop noexcept on Impl::ValueHierarchyNode::add_root_value() because the
specifiers make little sense there and they upset clang-tidy.

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppress clang-tidy warning on InitializationSettings getters

Signed-off-by: Damien L-G <dalg24@gmail.com>

* More bugprone-exception-escape suppressions

Signed-off-by: Damien L-G <dalg24@gmail.com>

* ViewCtorProp cleanup to resolve clang-tidy warning

Drop explicit defaulting of copy constructor and copy assignment
operator in ViewCtorProp which appear to resolve the following
clang-tidy warning:
```
<kokkos>/core/src/View/Kokkos_ViewCtor.hpp:183:8: warning: an exception may be thrown in function 'ViewCtorProp' which should not throw exceptions [bugprone-exception-escape]
  183 | struct ViewCtorProp : public ViewCtorProp<void, P>... {
      |        ^

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppressions for main

I opted for wholesale disabling in examples/tutorials to avoid poluting
our material with clang-tidy directives.
I think it is acceptable to annotate our tests and benchmarks.

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Enable bugprone-exception-escape check

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Strip noexcept specifier on all non-nested parallel_reduce

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Drop another couple bad noexcept specifier in "combined" reducers

Signed-off-by: Damien L-G <dalg24@gmail.com>

* Suppress nonsensical bugprone-exception-escape warning

Could not figure out where it is coming from and how to properly
resolve it but the suppression works.
```
/tmp/kokkos/algorithms/unit_tests/../src/std_algorithms/Kokkos_IterSwap.hpp:56:6: error: an exception may be thrown in function 'iter_swap<Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::LayoutStride, Kokkos::SYCLDeviceUSMSpace>>, Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::LayoutStride, Kokkos::SYCLDeviceUSMSpace>>>' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
   56 | void iter_swap(IteratorType1 a, IteratorType2 b) {
      |      ^
/tmp/kokkos/algorithms/unit_tests/../src/std_algorithms/Kokkos_IterSwap.hpp:56:6: error: an exception may be thrown in function 'iter_swap<Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::SYCLDeviceUSMSpace>>, Kokkos::Experimental::Impl::RandomAccessIterator<Kokkos::View<double *, Kokkos::SYCLDeviceUSMSpace>>>' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
```

Signed-off-by: Damien L-G <dalg24@gmail.com>

---------

Signed-off-by: Damien L-G <dalg24@gmail.com>